
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRLIT = 49;
  public static final int GREATERTHAN = 34;
  public static final int CLOSESB = 24;
  public static final int INCREMENT = 41;
  public static final int MULT = 29;
  public static final int CHAR = 6;
  public static final int QUESTIONMARK = 43;
  public static final int SEMI = 19;
  public static final int INT = 5;
  public static final int CLOSEP = 22;
  public static final int DECREMENT = 42;
  public static final int MINUS = 32;
  public static final int TILDE = 27;
  public static final int CLOSECB = 26;
  public static final int AND = 40;
  public static final int INTLIT = 45;
  public static final int ANGLEB = 38;
  public static final int EQUALTO = 37;
  public static final int OR = 39;
  public static final int LESSTHAN = 33;
  public static final int BOOL = 7;
  public static final int COMMA = 20;
  public static final int CLASS = 2;
  public static final int FI = 10;
  public static final int DIV = 30;
  public static final int OPENSB = 23;
  public static final int GEQ = 36;
  public static final int PLUS = 31;
  public static final int IF = 9;
  public static final int ID = 46;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int TRUE = 14;
  public static final int error = 1;
  public static final int PRINTL = 18;
  public static final int VOID = 4;
  public static final int OPENCB = 25;
  public static final int FLOATLIT = 48;
  public static final int ASSMNT = 28;
  public static final int CHARLIT = 47;
  public static final int COLON = 44;
  public static final int ELSE = 13;
  public static final int READ = 16;
  public static final int FINAL = 3;
  public static final int WHILE = 11;
  public static final int FLOAT = 8;
  public static final int LEQ = 35;
  public static final int FALSE = 15;
  public static final int OPENP = 21;
  public static final int PRINT = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "FINAL",
  "VOID",
  "INT",
  "CHAR",
  "BOOL",
  "FLOAT",
  "IF",
  "FI",
  "WHILE",
  "RETURN",
  "ELSE",
  "TRUE",
  "FALSE",
  "READ",
  "PRINT",
  "PRINTL",
  "SEMI",
  "COMMA",
  "OPENP",
  "CLOSEP",
  "OPENSB",
  "CLOSESB",
  "OPENCB",
  "CLOSECB",
  "TILDE",
  "ASSMNT",
  "MULT",
  "DIV",
  "PLUS",
  "MINUS",
  "LESSTHAN",
  "GREATERTHAN",
  "LEQ",
  "GEQ",
  "EQUALTO",
  "ANGLEB",
  "OR",
  "AND",
  "INCREMENT",
  "DECREMENT",
  "QUESTIONMARK",
  "COLON",
  "INTLIT",
  "ID",
  "CHARLIT",
  "FLOATLIT",
  "STRLIT"
  };
}

